export const REQUESTED_FIRST_PAGE = '[TODO] REQUESTED_FIRST_PAGE';
export const DATA_RECEIVED = '[TODO] DATA_RECEIVED';

export const ADD_ITEM = '[TODO] ADD_ITEM';
export const ADD_SEARCH = '[TODO] ADD_SEARCH';
export const ADD_COMMENT = '[TODO] ADD_COMMENT';

export const CHANGE_SELECTED_ITEM = '[TODO] CHANGE_SELECTED_ITEM';
export const CHANGE_ITEM_CONTENT = '[TODO] CHANGE_ITEM_CONTENT';

export const DELETE_ITEM = '[TODO] DELETE_ITEM';
export const DELETE_SEARCH_ITEM = '[TODO] DELETE_SEARCH_ITEM';

